dashbitco/nimble_parsec

lib/nimble_parsec.ex
`t` is defined using `combinator` which doesn't have a doc entry because it's private, so I figured it makes sense to make one of them opaque.
=> Make `t` opaque

lib/nimble_parsec.ex
=> Add warning for using `optional/2` and similar inside `repeat/2`

lib/nimble_parsec.ex, lib/nimble_parsec/compiler.ex, test/nimble_parsec_test.exs
Errors with multiple eof combinators might be awkward as its `end of file, followed by end of file`.
=> Add eof combinator

lib/nimble_parsec.ex
These abbreviations are officially spelled using uppercase letters, so
it's nice to follow that convention in the documentation.
=> Spell "ASCII" and "UTF-8" in their official forms

lib/nimble_parsec.ex
`MyParser.Helpers` was defined in duplicate. 
I deleted `.Helpers` from the second.
=> fix module name in Use cases doc

lib/nimble_parsec.ex, lib/nimble_parsec/compiler.ex
Similar to `unwrap_and_tag/3`, the `@spec` for `tag/3` was missing the third parameter leading to dialyzer errors.
=> Fix @spec for tag/3

lib/nimble_parsec/compiler.ex, test/nimble_parsec_test.exs
This PR extends the `:line` option when a parser is calling.
```elixir
...
defparsecp :digits, ascii_char([?0..?9]) 
...
digits("657", line: {2, 4}, byte_offset: 6)
```
This is useful to setup the start of the parser to a specific `{line, offset}` and `byte_offset`.
=> Add position as possible value for :line

lib/nimble_parsec.ex
As I was using NimbleParsec, I had to read source code to discover how to reference a remote combinator.
Maybe this isn't the way to do it, but it's the one I found!
Regardless, the spec for `parsec/2` is now more complete
=> docs: improve parsec/2 docs

lib/nimble_parsec/compiler.ex
Amended the documentation to clarify that `position` is `{line, byte_offset_to_start_of_line}` rather than `{line, column}` and clarifying how to calculate the error column.
=> Updated documentation about position

README.md
Just a minor annoyance I noticed the last three times I reached for nimble_parsec :)
=> Make the dep tuple easier to copy

lib/nimble_parsec.ex
Updated documentation for utf8_string/3:
* change references from ASCII to UTF8 and 
* note that results may vary depending on Unicode normalisation
=> Fix documentation for utf8_string/3

lib/nimble_parsec.ex, test/nimble_parsec_test.exs
After looking into #92, I think the problem may be that the `to_lookahead` arrays should be reversed, similarly as in `repeat`, `eventually`, etc. The snippet shared there, with or without the `|> debug()`, now has the same return value, so I hope this can close that issue.
Also, here is a more minimal snippet that illustrates the problem:
```elixir
defmodule Test do
import NimbleParsec
defparsec :parse, lookahead(utf8_char([?a]) |> utf8_char([?b]))
end
Test.parse("ab")
{:error,
"expected utf8 codepoint equal to 'b', followed by utf8 codepoint equal to 'a'",
"ab", %{}, {1, 0}, 0}
```
`lookahead_not` also behaves similarly.
Besides that test case, I also added 'nested' test cases which should maybe be dropped. I added them just because my first attempt at this issue added Enum.reverse …
=> Reverse inner combinators in lookahead and lookahead_not (fixes #92)

lib/nimble_parsec.ex
Both `repeat/3` and `choice/3` take a third optional parameter `opts` however `opts` is not included in the type spec. This PR adds an `opts` type and includes it in the type specs for `repeat/3` and `choice/3`.
=> Add opts to typespec for repeat and choice

lib/nimble_parsec.ex, lib/nimble_parsec/compiler.ex
I've added appropriate typespecs for functions with default arguments, this should fix dialyzer warning in #96.
In the second commit I've removed some parentheses for coherence with other type specs, but I'll happily drop it since it's 100% just for aesthetics.
=> Add typespecs for optional args

lib/nimble_parsec.ex
Thanks to @emilianobovetti for updating the type specs. There is one more to be added to `repeat/{1,3}` and this PR adds it.
=> Add additional spec for repeat/{1,3}

lib/nimble_parsec/compiler.ex, test/mix/tasks/nimble_parsec.compile_test.exs
Currently in some `lookahead_not` situations that is nested and tagged, there's a case where some generated code emits warnings of unused vars. This PR fixes those warnings.
I don't have a new assertion, but I did add some fixture code that exhibits the issue. I tried adjusting the `Mix.Task.run("compile")` call to treat warnings as errors to let that be the assertion, but it doesn't seem to be working as intended and compiling the generated code. Adjusting the `elixirc_paths` options for the project test env could fix this but maybe a bigger hammer than necessary.
When I add `debug: true` option to the new `lookahead_not_warning` fixture defparsec, this is what it outputs:
<details>
<summary>Before (full)</summary>
```elixir
defp lookahead_not_warning__0(<<"foo", rest::binary>>, acc, …
```
=> Avoid compile warnings with negative lookahead

lib/nimble_parsec/compiler.ex
Fixes #109.
It seems this path is only reached when ElixirLS is compiling the code and the pattern match was failing. I'm not sure why this is happening, maybe it has to do with the difference in line numbers in the generated ast?
=> Fix clause warning for integer combinator

lib/nimble_parsec.ex, test/nimble_parsec_test.exs
Hi, I hope this will fix https://github.com/dashbitco/nimble_parsec/issues/115
The issue was that `integer(max: 3)` combinator was matching "test" because it was transformed into `integer(min: 0, max: 3)`.
The is one check that verifies that `min > 0` but it is before the transformation.
I solved this splitting `integer(n)` from `integer(min: _, max: _)` and using the values returned from `validate_min_and_max/2`  to change the parameters before the tranformation
Hope it helps!
Thanks a lot :)
=> Integer combinator ensure at least 1 char

lib/nimble_parsec.ex
Adds a missing `ascii_char` call on the example string parser in `repeat_while`'s documentation
Closes #119
=> Fix example string parser in repeat_while docs

README.md
It wasn't updated after 8c946c4a9905f3b0491d715ed0385bc8afeced47
=> README: fix example return value

lib/nimble_parsec.ex, lib/nimble_parsec/compiler.ex, test/nimble_generator_test.exs, test/nimble_parsec_test.exs
This pull request adds a new `bytes/2` combinator ( #131). This combinator allows a user to pull the next `n` bytes from the input. It will compile to a `binary-size` pattern match on the input string and will return a parsing error if there are insufficient bytes.
@josevalim, I know that in #30, you proposed a `binary_size` combinator which seems to take this idea further. From what I can tell, it would add similar compile time optimizations to other bounded combinators. However, `bytes` was also included as a secondary combinator in that proposal.
=> add bytes/2 combinator

lib/nimble_parsec/compiler.ex
This fixes the type of `byte_offset` to allow for `0` without dialyzer warnings. When parsing a pattern starting at the beginning of a string, it's normal for this to be 0. Also, in the generated options, `:byte_offset` is 0.
https://github.com/dashbitco/nimble_parsec/blob/0ccc43e025b45dbb85d6f2f0ac0e2856ef6cd57f/lib/nimble_parsec/compiler.ex#L20
=> Fix type of byte_offset

lib/nimble_parsec.ex
Hello there,
A small PR/question regarding the `optional` combinator documentation.
I might be wrong, but it seems that `optional` combinator documentation should mention `combinator` instead of `optional` in this case:
```diff
-  It is equivalent to `choice([optional, empty()])`.
+  It is equivalent to `choice([combinator, empty()])`.
```
=> Update `optional` combinator documentation

examples/simple_xml.exs
> warning: returning a two-element tuple {acc, context} in pre_traverse/post_traverse
> is deprecated, please return {rest, acc, context} instead
>   SimpleXML.node__31/6
>   SimpleXML.parse__0/6
>   SimpleXML.parse/2
>   examples/simple_xml.exs:50: anonymous fn/1 in :elixir_compiler_2.__FILE__/1
>   (elixir 1.17.0-rc.1) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
>   (elixir 1.17.0-rc.1) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
=> Fix deprecation warning on SimpleXML example

.github/workflows/ci.yml, README.md
See https://hexdocs.pm/elixir/1.17.1/compatibility-and-deprecations.html
List of changes:
- use Erlang (22 and 27) and Elixit (~1.13~ 1.12 and 1.17) in GitHub CI.
- add related CI and Hex badges
- ~set minimum Elixir version to 1.13~
=> CI housekeeping

.github/workflows/ci.yml
Additional changes:
- bump GitHub Actions
- specify versions as strings, not numbers, see https://github.com/erlef/setup-beam?tab=readme-ov-file#specify-versions-as-strings-not-numbers
- use major versions which resolves to latest version
=> Support Elixir 1.18 in GitHub CI
